export const LOAD_HIGHSCORES_STARTED = 'cooksys/whos-who/ducks/highscores/LOAD_HIGHSCORES_STARTED'
export const LOAD_HIGHSCORES_FAILED = 'cooksys/whos-who/ducks/highscores/LOAD_HIGHSCORES_FAILED'
export const LOAD_HIGHSCORES_SUCCESS = 'cooksys/whos-who/ducks/highscores/LOAD_HIGHSCORES_SUCCESS'
export const SAVE_HIGHSCORES_STARTED = 'cooksys/whos-who/ducks/highscores/SAVE_HIGHSCORES_STARTED'
export const SAVE_HIGHSCORES_FAILED = 'cooksys/whos-who/ducks/highscores/SAVE_HIGHSCORES_FAILED'
export const SAVE_HIGHSCORES_SUCCESS = 'cooksys/whos-who/ducks/highscores/SAVE_HIGHSCORES_SUCCESS'
export const ADD_HIGHSCORES_NEW = 'cooksys/whos-who/ducks/highscores/ADD_HIGHSCORES_NEW'
